default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  only:
    - dev
  script:
    - npm install vercel
    - ./node_modules/.bin/vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel build --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel deploy --prebuilt  --token=$VERCEL_TOKEN

# deploy_production:
#   stage: deploy
#   only:
#     - main
#   script:
#     - npm install vercel
#     - ./node_modules/.bin/vercel pull --yes --environment=production --token=$VERCEL_TOKEN
#     - ./node_modules/.bin/vercel build --prod --token=$VERCEL_TOKEN
#     - ./node_modules/.bin/vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  script:
    - ssh "$DEV_USER@$DEV_HOST" './killall-hub-process.sh || true'
    - ssh "$DEV_USER@$DEV_HOST" 'rm -rf ~/deodd || true'
    - ssh "$DEV_USER@$DEV_HOST" 'mkdir -p ~/deodd/ || true'
    - scp -r ./* "$DEV_USER@$DEV_HOST:~/deodd/"
    - ssh "$DEV_USER@$DEV_HOST" "cd deodd; yarn install; yarn build"
    - ssh "$DEV_USER@$DEV_HOST" "cd deodd; yarn start -p 3001 > /dev/null 2>&1 &"
  only:
    - main
  when: manual